### ISSUE TITLE
Partials and assets are not loading.

### ISSUE THREAD

**Issue by askari12** [huseyintaskesen/CS353_Database_Project#1]
Views do not work with the basic structure. The images and partials are not running.

What did you add in your server files to make them run?

**Comment by huseyintaskesen** [comment]
i will update the server.js that you upload. sounds good?

**Comment by askari12** [comment]
Can you send it as a separate file ?

**Comment by bilalsiraj** [comment]
Apparently it works now so I'm closing this issue.
